---
- hosts: k3s_cluster
  vars:
    k3s_version: v1.19.3+k3s2
  gather_facts: yes
  become: yes
  roles:
    - role: k3s/prereq
    - role: k3s/download
    - role: k3s/pi

- hosts: master
  become: yes
  roles:
    - role: k3s/master

- hosts: node
  become: yes
  roles:
    - role: k3s/node
