- hosts: "{{ hostname }}"
  vars:
    admin_keys:
      tas:
        - "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

    raspberry_pi_boot_config_options:
      # Set the GPU memory split value.
      - regexp: "^#?gpu_mem"
        line: "gpu_mem=16"
      # Enable 1200ma USB current on newer model Pis.
      - regexp: "^#?max_usb_current"
        line: "max_usb_current=1"

    raspberry_pi_rc_local_options:
      # Disable HDMI on startup (for power savings).
      - regexp: "^/usr/bin/tvservice"
        line: "/usr/bin/tvservice -o"

  roles:
    - { role: raspberry-pi, become: true }
    - { role: user, username: tas, become: true }
    - { role: static-ip }

  tasks:
    - name: Install basic packages
      become: true
      apt: package={{ item }} state=present
      with_items:
        - vim-nox
        - screen
        - htop

    # Set vim as default editor
    - alternatives: name=editor path=/usr/bin/vim.tiny
      become: true

    - name: Clear motd
      become: true
      copy: dest=/etc/motd content=""

    - name: Remove uname on login
      become: true
      lineinfile:
        dest: /etc/update-motd.d/10-uname
        regexp: "^uname"
        line: "# uname -snrvm"

  vars_prompt:
    - name: "hostname"
      prompt: "Hostname"
      private: no
    - name: "interface"
      prompt: "Ethernet interface"
      default: "eth0"
      private: no
    - name: "ipaddress"
      prompt: "Static IPv4 address"
      private: no
    - name: "routers"
      prompt: "Routers (comma separated)"
      default: "192.168.0.1"
      private: no
    - name: "dns_servers"
      prompt: "DNS servers (space separated)"
      default: "8.8.8.8 8.8.4.4"
      private: no
