- hosts: {{inventory_hostname}}
  vars:
    admin_keys:
      TAS:
      - {{ lookup("file", "~/.ssh.=/id_rsa.pub" }}

    raspberry_pi_boot_config_options:
      # Set the GPU memory split value.
      - regexp: "^#?gpu_mem"
        line: "gpu_mem=16"
      # Enable 1200ma USB current on newer model Pis.
      - regexp: "^#?max_usb_current"
        line: "max_usb_current=1"

    raspberry_pi_rc_local_options:
      # Disable HDMI on startup (for power savings).
      - regexp: "^/usr/bin/tvservice"
        line: "/usr/bin/tvservice -o"

  roles:
    - { role: raspberry-pi }
    - { role: user, username: TAS }

  tasks:

    - name: Install basic packages
      apt: package={{ item }} state=present
      with_items:
      - vim-nox
      - screen
      - htop

    # Set vim as default editor
    - alternatives: name=editor path=/usr/bin/vim.tiny

    - name: Clear motd
      copy: dest=/etc/motd content=""

    - name: Remove uname on login
      lineinfile:
        dest: /etc/update-motd.d/10-uname
        regexp: '^uname'
        line: '# uname -snrvm'

    - name: Add welcome screen
      copy: dest=/home/welcome.sh content={{ lookup("file", "./src/motd/welcome.sh" }}
