---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- name: "Update APT package cache"
  become: yes
  action: apt update_cache=yes

- name: "Upgrade APT to the lastest packages"
  become: yes
  action: apt upgrade=safe

- name: Configure options in /boot/config.txt.
  become: true
  lineinfile:
    dest: /boot/config.txt
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: EOF
    state: present
  with_items: "{{ raspberry_pi_boot_config_options }}"
  register: boot_config

- name: Configure options in /etc/rc.local.
  become: true
  lineinfile:
    dest: /etc/rc.local
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "^exit"
    state: present
  with_items: "{{ raspberry_pi_rc_local_options }}"
  register: rc_local_config

- name: Configure hostname in /etc/hostname.
  become: true
  command: hostnamectl set-hostname "{{ hostname }}"
  # lineinfile:
  #   path: /etc/hostname
  #   regexp: "^raspberrypi"
  #   line: "{{ hostname }}"
  #   owner: root
  #   group: root
  #   mode: "644"
  register: hostname

- name: Configure host in /etc/hosts.
  become: true
  ignore_errors: true
  lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1    {{ hostname }}"
    owner: root
    group: root
    mode: "644"
  register: hosts

- name: "Reboot"
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true
  when: boot_config.changed or rc_local_config.changed or hostname.changed or hosts.changed
  register: reboot

- name: "Wait for Raspberry PI to come back"
  local_action: wait_for host={{ real_ansible_host }} port=22 state=started delay=10
  become: false
  when: reboot.changed
